name: Backend CD

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ secrets.BACKEND_ECR_URI }}:${{ github.sha }}
        docker build -t $IMAGE_URI ./backend
        docker push $IMAGE_URI

    - name: Deploy Backend to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs/backend-task-def.json
        service: backend-service
        cluster: my-ecs-cluster
        wait-for-service-stability: true
