name: Backend CI/CD

on:
  push:
    branches:
      - feature/backend
  pull_request:
    branches:
      - develop

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests (if available)
        run: |
          cd backend
          pytest || echo "No tests found"

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        env:
          ECR_REPO: ${{ secrets.ECR_BACKEND_REPO }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd backend
          docker build -t $ECR_REPO:latest .
          docker push $ECR_REPO:latest
