name: Frontend CI

on:
  push:
    branches:
      - feature/frontend
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          yarn install || npm install

      - name: Build frontend
        run: |
          cd frontend
          yarn build || npm run build

      - name: Test Docker build (optional)
        run: |
          cd frontend
          docker build -t frontend-test:latest .
