name: Terraform CI

on:
  push:
    branches:
      - feature/terraform
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: |
          cd terraform
          terraform init -backend=false

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
